### ISSUE TITLE
Difference between this scraping and Brasil.io's

### ISSUE THREAD

**Issue by augusto-herrmann** [capyvara/brazil-civil-registry-data#2]
By reading the README.me, I couldn't understand what is the difference between this scraping of the data and the one [already available for download at Brasil.io](https://brasil.io/dataset/covid19/obito_cartorio/). Perhaps this could be made clearer in the text.

**Comment by capyvara** [comment]
Obrigado! adicionei informações la:

- [Brasil.IO](https://brasil.io): 
    - https://brasil.io/dataset/covid19/obito_cartorio/
    - There you can find the equivalent of the civil_registry_covid_states.csv (except no death places) in a easier to digest format
    - Here you can contribute to it: https://github.com/turicas/covid19-br
    - There are plans to bring all the data on this repo to it in a near future
