### ISSUE TITLE
Include administrative regions in DF

### ISSUE THREAD

**Issue by capyvara** [capyvara/brazil-civil-registry-data#3]
O cartório civil retorna as regiões administrativas em separado: Brasilia, Ceilandia, Gama, Guara, etc.

Temos duas opções:
- Agregamos tudo como se fosse brasilia
- Mantemos separado e assumimos que alem de cidades vai entrar regiões administrativas (codigos mais longos)

**Comment by beatrizjardim** [comment]
Acho mais adequado agregar tudo como Brasília. Se não me engano, a programação de saúde de lá é para DF como um todo.

**Comment by capyvara** [comment]
Arrumado no commit a043e3d32b3f3111a72712cf0243fcc9786d858d, agora Brasilia contém dados do estado DF inteiro.
