### ISSUE TITLE
Add home city

### ISSUE THREAD

**Issue by capyvara** [capyvara/brazil-civil-registry-data#7]
Agora tem um campo "cidade_id_tipo": "cityFalecimento", parece que vão adicionar a opcao de cidade de residência.

Quão importante é esse dado, faz sentido colocar no mesmo .csv?

**Comment by beatrizjardim** [comment]
Importante para saber identificar a cidade de registro/residência.
Para os estudos epidemiológicos, faz diferença saber a cidade de residência.

Em seg, 13 de jul de 2020 14:17, Marcelo Oliveira <notifications@github.com>
escreveu:

**Comment by oranzani** [comment]
Concordo com a Beatriz. Essa informação vai ser super importante para ver onde está ocorrendo mais infecções, já que local de óbito é mais variável. Também para estabilização dos outros anos, já que a população 2019, 2018, 2017 etc é muito mais estável por residência do que por ocorrência. Marcelo, acho que você vai precisar de extrair um arquivo inteiro por residência e outro por ocorrência, não?

**Comment by thomas-fujiwara** [comment]
Eh importante sim, eu tb acho, ate pq em umas cidades os dados da arpen nao batem com o SIM e tem a questao de “as pessoas vao ate a capital para se internar e morrem la”.

Eu acho q 2 versoes separadas, uma por cidade de ocorrência e outra por residência, seria otimo.

**Comment by thomas-fujiwara** [comment]
Eu quero dizer, acho q perder a info de qtos residentes de cidade x morrem em cidade y nao eh um problema, eh mais util ter os totais por cada tipo.

**Comment by beatrizjardim** [comment]
Seria um complicador ter a base por registro mas ter uma coluna para a
cidade de ocorrência e outra para a cidade de residência?

Em seg., 13 de jul. de 2020 às 15:09, thomas-fujiwara <
notifications@github.com> escreveu:

**Comment by capyvara** [comment]
Adicionaram um campo 
![image](https://user-images.githubusercontent.com/1027847/88745966-b04a3280-d121-11ea-9a2a-601357bc175d.png)

Realmente não sei como fazer nesse caso, achei que o filtro ia me dar qto de casos por cidade.

Que acham?

**Comment by thomas-fujiwara** [comment]
Eu pessoalmente acho que nao vou usar esse filtro - pq nao da para pegar os obitos por municipio de residencia por ele. Em principio voce poderia escolher um scrape e fazer a versao "somente obitos de nao residentes." Mas eu nao sei se vale a pena dado que toma tempo/etc.

**Comment by beatrizjardim** [comment]
Estou na mesma que o Thomas. Se tivesse um campo que possibilitasse a
identificação do município de residência, seria ótimo. Esse seletor me
remete à ideia de fazer o inverso: somente óbitos de residentes. Mas acho
que perderíamos muita informação, sobretudo do interior.


Em qua., 29 de jul. de 2020 às 15:58, thomas-fujiwara <
notifications@github.com> escreveu:

**Comment by capyvara** [comment]
É esse jeito que eles fizeram perdeu muito do sentido
E vc @oranzani ?

**Comment by oranzani** [comment]
Concordo com o pessoal. Deste jeito a utilidade é bem baixa, já que não conseguiremos ter o dado por residência. E o que acho perigoso: como com a pandemia as pessoas, em teoria, mudam menos de cidade para tratamento, a comparação com 2019 pode ter viés que não conseguimos prever.
Eu não adicionaria esse filtro neste momento. Obrigado.
